services:
  quizz-db:
    image: mongo
    restart: always
    env_file:
      - ./apps/keyrigme-back/.env
    ports:
      - "27017:27017"
    volumes:
      - ./apps/keyrigme-back/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data-quizz:/data/db

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    env_file:
      - ./apps/keyrigme-back/.env


volumes:
  mongo-data-songs:
    driver: local
  mongo-data-quizz:
    driver: local