export const QuizzEventName = {
  AddPlayer: 'addPlayer',
  CreateRoom: 'createRoom',
  UpdateRoomConfig: 'updateRoomConfig',
  RoomConfigUpdated: 'roomConfigUpdated',
  EndQuizz: 'endQuizz',
  QuizzStarted: 'quizzStarted',
  JoinRoom: 'joinRoom',
  LeaveRoom: 'leaveRoom',
  NewRoundData: 'newRoundData',
  PlayerAnswer: 'playerAnswer',
  RemovePlayer: 'removePlayer',
  RemovedPlayer: 'removedPlayer',
  RoomCreated: 'roomCreated',
  RoomJoined: 'roomJoined',
  SetUserPoints: 'setUserPoints',
  ShowAnswers: 'showAnswers',
  ChangeIndexAnswers: 'changeIndexAnswers',
  ShowResult: 'showResult',
  StartQuizz: 'startQuizz',
  Error: 'error',
} as const;